# arr: task order
# train_data_dir: train dataset path
# file_name: corresponding replay data that generated by InsCL_sampling
arr=('Classification' 'Text_Quality_Evaluation' 'Code' 'Detection' 'Sentiment_Analysis' 'Comprehension' 'Closed_QA' 'Extraction' 'Dialogue' 'Program_Execution' 'Rewriting' 'Open_QA' 'Misc' 'Generation' 'Summarization' 'Mathematics')
train_data_dir='../dataset/train'
file_name='InsCL_curriculum_pWdist_seed1_num200_eps0.1_5'
repaly_data_dir="replay_data/${file_name}"
target_dir="merge_train/${file_name}"
mkdir ${target_dir}

for i in {0..15}
do
echo "cat ${train_data_dir}/${arr[i]}.jsonl to ${target_dir}/${arr[i]}.jsonl"
cp ${train_data_dir}/${arr[i]}.jsonl ${target_dir}/${arr[i]}.jsonl
if [ $i != 0 ]; then
echo "start merge ${repaly_data_dir}/${arr[i]}.jsonl to ${target_dir}/${arr[i]}.jsonl"
cat ${repaly_data_dir}/${arr[i]}.jsonl >> ${target_dir}/${arr[i]}.jsonl
fi
echo -e "\n"
done